abstract final class AppRoutes {
  static const splash = '/splash';
  static const onboarding = '/onboarding';
  static const home = '/home';
  static const categories = '/categories';
  static const productDetail = '/product-detail';
  static const checkout = '/checkout';
  static const paymentSuccess = '/payment-success';
  static const addressForm = '/address';
  static const productList = '/products';
  static const personalInformation = '/personal-information';
  static const changePassword = '/change-password';
  static const contactUs = '/contact-us';
  static const myOrders = '/my-orders';
  static const login = '/login';
  static const register = '/register';
  static const forgotPassword = '/forgot-password';
  static const otpVerification = '/otp-verification';
  static const resetPassword = '/reset-password';
  static const passwordUpdated = '/password-updated';
}
